---
- name: Install Docker, Docker Compose, and Nginx
  hosts: ankit_ec2
  become: true

  tasks:
    - name: Install Docker
      shell: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Install Docker Compose
      shell: |
        sudo apt-get install -y docker-compose

    - name: Install Nginx
      apt:
        name: nginx
        state: present

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
